[PT-1603] Use builder pattern
CancerAidDev/elm-form-builder pull request #39
Opened 2023-01-16 05:05 UTC by cedliang

See example for usage of builder pattern

2023-01-16 05:29 UTC, dendrei requested changes
Nice work just a few things to look at

2023-01-16 05:29 UTC, dendrei commented on examples/Fields.elm
> +                >> FormField.setDisabled
```suggestion
        , FormField.email
            |> FormField.setLabel "Not relevant Email Address"
            |> FormField.setOrder order
            |> FormField.setDisabled
```

I was thinking an api more along these lines

2023-01-16 05:29 UTC, dendrei commented on src/Form/Field.elm
> +    , AgeFieldProperties, CommonFieldProperties, DateFieldProperties, SimpleFieldProperties, SelectFieldProperties, HttpSelectFieldProperties, MultiSelectFieldProperties, SearchableMultiSelectFieldPr
We could clean up the API of Field and not expose as much

2023-01-17 00:44 UTC, cedliang commented on examples/Fields.elm
> +                >> FormField.setDisabled
I considered this but the problem is if the setters are defined in terms of mutating a ready constructed `Field` instead of field property records, we'd end up with a lot of
```
    case field of
        MultiStringField_ multiStringField ->
            MultiStringField_ <| updateTagsValue_ addTag value multiStringField

        _ ->
            field
```
and these wouldn't get type inferenced - there'd be nothing stopping someone putting a setDate on a multiselect field, it would just do nothing. We have existing setters but they suffer from this issue, and I think should only be there for last resort. I think Elm isn't well equipped for this type of stuff because putting each type of `Field` in a branch of a union type makes deconstruction a bit of a pain, but I don't see a better solution without typeclasses.

So realistically mutating the records before constructing them is unavoidable, it'll be either this syntax or 

```
FormField.emailDefault
            |> FormField.setLabel "Not relevant Email Address"
            |> FormField.setOrder order
            |> FormField.setDisabled
            |> mkEmail
```
where mkEmail is something like `StringField_ << SimpleField`.

2023-01-17 01:10 UTC, dendrei commented on examples/Fields.elm
> +                >> FormField.setDisabled
Yep that later approach sounds good. I've seen a few packages with that interface (e.g. some of the components in https://package.elm-lang.org/packages/rundis/elm-bootstrap/5.2.0/)

2023-01-17 02:07 UTC, cedliang commented on src/Form/Field.elm
> +    , AgeFieldProperties, CommonFieldProperties, DateFieldProperties, SimpleFieldProperties, SelectFieldProperties, HttpSelectFieldProperties, MultiSelectFieldProperties, SearchableMultiSelectFieldPr
I'll try to figure out which of these I can refactor into modules that are available to other modules in the package but not exposed externally

2023-01-17 02:13 UTC, cedliang commented on src/Form/Field.elm
> +    , AgeFieldProperties, CommonFieldProperties, DateFieldProperties, SimpleFieldProperties, SelectFieldProperties, HttpSelectFieldProperties, MultiSelectFieldProperties, SearchableMultiSelectFieldPr
Never mind, doesn't seem possible to import a definition but not re-export it. Hmm, this might be tough since some of these definitions are used across a few modules here to reuse code across the lib, but shouldn't be necessarily exposed as part of the API.

2023-01-17 23:13 UTC, cedliang commented on src/Form/Field.elm
> +    , AgeFieldProperties, CommonFieldProperties, DateFieldProperties, SimpleFieldProperties, SelectFieldProperties, HttpSelectFieldProperties, MultiSelectFieldProperties, SearchableMultiSelectFieldPr
Tried some more changes but I don't think they're worth keeping around, I think this might be the best we can do

2023-08-23 06:33 UTC, dendrei approved these changes

2023-08-23 06:33 UTC, merged